channels:
  welcome: 708732557453426728
  gamechat: 597852843785060357
  notifications: 701824005954600960
ingame_regex: '^`[A-Za-z]+` \*\*([A-Za-z0-9_\\]+)\*\*: *(.*)$'
notifications:
  - name: "ðŸ‡¸urvival"
    description: "Survival updates"
    role: 701802551175282759
  - name: "ðŸ‡ºpdates"
    description: "Network updates"
    role: 702192714862821485
  - name: "ðŸ‡¨ompetitor"
    description: "Competition involvement"
    role: 755068314186940486
  - name: "ðŸ‡µoL"
    description: "Plot o' Logic Revamp"
    role: 846135848226652191
  - name: "ðŸ‡¹rial"
    description: "Get notified by Staff for trials"
    role: 1295904929378074725
roles:
  trusted: 962782039403298887
  staff: 617848463438118922
  admin: 117711708847472645
logging_level: "WARN"
greetings:
  - "Welcome to ORE, {user}! Make sure to run `/discord` ingame and link your account to view the rest of DiscOREd!"
  - "Oh hi, {user}! Run `/discord` ingame to link your account to view the rest of DiscOREd!"
  - "Welcome, {user}! To see the rest of our DiscOREd, link your account by running `/discord` ingame!"
insults:
  - "once in the 4th grade {user} got a 2% on their math quiz so everyone called them milk for the rest of the year"
  - "{user} may look like an idiot and talk like an idiot but don't let that fool you. {user} really is an idiot."
  - "{user}, you warthog-faced buffoon."
  - "{user}, I fart in your general direction. Your mother was a hamster and your father smelt of elderberries."
  - "{user} has no enemies, but is intensely disliked by their friends."
  - "{user} is a cockalorum."
  - "{user} ........ pillock."
  - "{user} is more disappointing than an unsalted pretzel."
  - "{user} is the reason God created the middle finger."
  - "Iâ€™ll never forget the first time I met {user}. But Iâ€™ll keep trying."
  - "Hold still. Iâ€™m trying to imagine {user} with a personality."
protips:
  - "<:ore_seth:936109518029484052>"
  - "for legal reasons, this is a joke"
  - "if music was a woman id marry her"
